//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekat_Bioskop
{
    using System;
    using System.Collections.Generic;
    
    public partial class KORISNICI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KORISNICI()
        {
            this.RADNICIs = new HashSet<RADNICI>();
        }
    
        public int korisnik_id { get; set; }
        public string korisnickoIme { get; set; }
        public string lozinka { get; set; }
        public string tip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RADNICI> RADNICIs { get; set; }
    }
}
