//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekat_Bioskop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRIKAZIVANJA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRIKAZIVANJA()
        {
            this.PRODATE_KARTE = new HashSet<PRODATE_KARTE>();
        }
    
        public int prikazivanje_id { get; set; }
        public int id_filma { get; set; }
        public System.DateTime pocetak_prikazivanja { get; set; }
        public System.DateTime kraj_prikazivanja { get; set; }
        public int status_prikazivanja { get; set; }
    
        public virtual FILMOVI FILMOVI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODATE_KARTE> PRODATE_KARTE { get; set; }
    }
}
