//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekat_Bioskop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODATE_KARTE
    {
        public int karta_id { get; set; }
        public string prostorija { get; set; }
        public string broj_reda { get; set; }
        public short broj_sjedista { get; set; }
        public string status_sjedista { get; set; }
        public string datum { get; set; }
        public string termin { get; set; }
        public int id_prikazivanja { get; set; }
    
        public virtual PRIKAZIVANJA PRIKAZIVANJA { get; set; }
    }
}
