//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekat_Bioskop
{
    using System;
    using System.Collections.Generic;
    
    public partial class RADNICI
    {
        public int radnik_id { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public System.DateTime datum_rodjenja { get; set; }
        public string adresa { get; set; }
        public string telefon { get; set; }
        public System.DateTime datum_zaposlenja { get; set; }
        public Nullable<System.DateTime> kraj_zaposlenja { get; set; }
        public int id_korisnika { get; set; }
    
        public virtual KORISNICI KORISNICI { get; set; }
    }
}
